obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.19, -0.12], [-0.19, 0.12], [0.19, 0.12], [0.19, -0.12]]
#footprint_padding: 0.01    # rbx1 no
# robot_radius: 0.1


inflation_radius: 0.1 # rbx1 0.2  0.05



# NavfnROS:                   # rbx1 no
#     allow_unknown: true   # rbx1 no

max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.5}

#    sensor:
#        observation_sources: base_scan
#        base_scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0}
