local_costmap:
#    footprint: [[-0.12, -0.19], [-0.12, 0.19], [0.12, 0.19], [0.12, -0.19]]
#robot_radius: 0.1


#   global_frame: /odom
   global_frame: /map       #  rbx1 fake setting
   robot_base_frame: /base_link

   update_frequency: 4.0   #  rbx1 3
   publish_frequency: 2.0   #  rbx1 1


#   static_map: false
#   rolling_window: true
   static_map: true      #  rbx1 fake setting
   rolling_window: false   #  rbx1 fake setting



#   width: 0.5     # <!-- rbx1  value="6.0"/-->
   width: 6.0     # <!-- rbx1  value="6.0"/-->
#   height: 0.5    # <!-- rbx1  value="6.0"/-->
   height: 6.0    # <!-- rbx1  value="6.0"/-->

   resolution: 0.01  # <!-- rbx1  value="0.01"/-->
#   resolution: 0.05  # <!-- rbx1  value="0.01"/-->
   transform_tolerance: 1.0

   map_type: costmap   #  rbx1 no


#    plugins:            
#        - {name: sensor,     type: "costmap_2d::ObstacleLayer"}
#        - {name: inflation,  type: "costmap_2d::InflationLayer"}

#    sensor:
#        observation_sources: base_scan
#        base_scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#    inflation:

#        cost_scaling_factor: 10.0
