obstacle_range: 1.0
raytrace_range: 2.0

footprint: [[-0.19, -0.14], [-0.19, 0.14], [0.19, 0.14], [0.19, -0.14]]
#footprint_padding: 0.01    # rbx1 no
# robot_radius: 0.1


inflation_radius: 0.05
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
