## USB port
port: /dev/razor_imu_10736


##### Calibration ####
### accelerometer
accel_x_min: -291.00
accel_x_max: 280.00
accel_y_min: -260.00
accel_y_max: 296.00
accel_z_min: -322.00
accel_z_max: 241.00

### magnetometer
# standard calibration
magn_x_min: -731.00
magn_x_max: 844.00
magn_y_min: -771.52
magn_y_max: 825.00
magn_z_min: -764.00
magn_z_max: 755.00

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [93.7352, 19.6168, -8.21720]
magn_ellipsoid_transform: [[0.913161, 0.0116277, 0.00383255], [0.0116277, 0.924952, 0.0218212], [0.00383255, 0.0218212, 0.993043]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 41.85
gyro_average_offset_y: 56.59
gyro_average_offset_z: -3.55
