## USB port
port: /dev/razor_imu_10736


##### Calibration ####
### accelerometer
accel_x_min: -275.00
accel_x_max: 286.00
accel_y_min: -272.00
accel_y_max: 292.00
accel_z_min: -327.00
accel_z_max: 236.00

### magnetometer
# standard calibration
magn_x_min: -343.00
magn_x_max: 495.00
magn_y_min: -366.00
magn_y_max: 354.00
magn_z_min: -359.00
magn_z_max: 326.00

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [84.4557, 12.6689, -1.23583]
magn_ellipsoid_transform: [[0.919921, 0.00784221, 0.00630756], [0.00784221, 0.919412, 0.0183434], [0.00630756, 0.0183434, 0.994999]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 41.64
gyro_average_offset_y: 59.69
gyro_average_offset_z: -4.69
